### ISSUE TITLE
Inline TopoJSON

### ISSUE THREAD

**Issue by janwendt** [jimmyrocks/maplibre-gl-vector-text-protocol#4]
Hi!
How can I use inline topojson? Geojson can be passed inline to MapLibre via the data attribute e.g.
'data': {...}
instead of
'data': 'https://....json' or a local file path.
With maplibre-gl-vector-text-protocol and topojson this does not work. 
Thank you!

**Comment by jimmyrocks** [comment]
Hello,

This is a really good question! The code is written to require a URL and it pulls the raw data and then processes it. There isn't really a way to go around the URL requirement either.

You may want to look into the [topojson-client](https://github.com/topojson/topojson-client) library, which is what this plugin uses to convert topojson.

You can still use this plugin, but I'd suggest using a JavaScript Object URL (which basically converts data into a URL) like this:
```JavaScript
const topojsonData = {...};  // Your TopoJSON data
const blob = new Blob([JSON.stringify(topojsonData)], {type: 'application/json'});
const topojsonUrl = URL.createObjectURL(blob);
```

You should also revoke that ObjectURL once the topojson source loads to prevent memory leaks:
```JavaScript
  const onSourceData = function(e) {
    if (e.sourceId === 'yourSourceId' && e.isSourceLoaded) {
      // Revoke the Blob URL
      URL.revokeObjectURL(topojsonUrl);
      // Remove the listener
      map.off('sourcedata', onData);
    }
  }

  map.on('sourcedata', onSourceData);
```

You could then assemble this all into code like this:
```JavaScript
  const map = new maplibregl.Map({
      container: 'map', // container id
      style: 'https://demotiles.maplibre.org/style.json', // style URL
      center: [-74.8306, 39.06], // starting position [lng, lat]
      zoom: 9 // starting zoom
  });

  // Add the sources for all the types
  VectorTextProtocol.addProtocols(maplibregl);

// Extra code for the TOPOJSON conversion
  const topojsonSourceName = '...'; // Your TopoJSON Source Name
  const topojsonData = {...};  // Your TopoJSON data
  const blob = new Blob([JSON.stringify(topojsonData)], {type: 'application/json'});
  const topojsonUrl = URL.createObjectURL(blob);

  const onSourceData = function(e) {
    if (e.sourceId === topojsonSourceName && e.isSourceLoaded) {
      // Revoke the Blob URL
      URL.revokeObjectURL(topojsonUrl);
      // Remove the listener
      map.off('sourcedata', onSourceData);
    }
  }
  map.on('sourcedata', onSourceData);

  map.on('load', () => {
    const topojsonLink = 'topojson://' + topojsonUrl;
    map.addSource(topojsonSourceName, {
        'type': 'geojson',
        'data': topojsonLink,
    });
    map.addLayer({
        'id': 'Layer' + topojsonSourceName,
        'type': 'fill',
        'source': topojsonSourceName,
        'minzoom': 0,
        'maxzoom': 20,
        'paint': {
            'fill-opacity': 0.25,
            'fill-color': 'yellow',
            'fill-outline-color': 'gray'
        }
    });
  });
```

Let me know how that works for you, or if you have any further questions.

--
"jimmyrocks"

**Comment by janwendt** [comment]
It works. 

Unfortunately it is quite slow so I do not know if I will use it. In comparison, when I load geojson that is on my hard drive, it loads much faster even though the file is bigger.

Originally I wanted to import the TopoJson directly via "topojson://./xyz.json", but since I bundle the project with webpack the json has to be imported via webpack "import topojsonData from './topo.json'" and then passed to maplibre-gl-vector-text-protocol directly.

**Comment by jimmyrocks** [comment]
That is a little tricky. I'd be curious how the [topojson-client](https://github.com/topojson/topojson-client) library would work, since that's what this tool is using in the backend.
