### ISSUE TITLE
Release on NPM?

### ISSUE THREAD

**Issue by Pete-Y-CS** [jimmyrocks/maplibre-gl-vector-text-protocol#5]
Hi, 
I hope I'm not missing something obvious, but can this be added to a project via npm and if not are there plans to make this possible? I am working on a project where we probably want to use this package but not directly inside a webpage so I'm not sure if the recommended method of `<script src="https://loc8.us/maplibre-gl-vector-text-protocol/dist/maplibre-gl-vector-text-protocol.js"></script>` works for our use case.

Any suggestions?

Cheers,
Pete

**Comment by jimmyrocks** [comment]
I have been thinking about creating an NPM package for this. I've actually never done it, so there will be a learning curve for it, but I think it should be possible. Are you using Webpack, Rollup, or something else to compile your website? This project uses Rollup.

**Comment by Pete-Y-CS** [comment]
We're using Svelte, which uses Vite to build.

**Comment by georgek** [comment]
Great library! I'm sure you'll find publishing to npm quite straightforward. Definitely recommend it for visibility and easy of use.

In the meantime, it can be installed directly from GitHub like so:

`npm install git+https://github.com/jimmyrocks/maplibre-gl-vector-text-protocol.git`

**Comment by jimmyrocks** [comment]
I finally got this up in NPM: https://www.npmjs.com/package/maplibre-gl-vector-text-protocol
