### ISSUE TITLE
Not working with maplibre-gl v4

### ISSUE THREAD

**Issue by georgek** [jimmyrocks/maplibre-gl-vector-text-protocol#7]
Looks like `addProtocol` has changed in maplibre-gl v4 and this library is not working.

**Comment by jimmyrocks** [comment]
Thanks for bringing this up! I have a fix ready to go, I’ll get it pushed tonight.

**Comment by jimmyrocks** [comment]
The library will now detect version 3 or 4 of maplibre and work accordingly. More info at this commit: https://github.com/jimmyrocks/maplibre-gl-vector-text-protocol/commit/e514aa41ea1a3c03970c8fba7544a3d23a79d84b
